
# [env]
# TERM = "alacritty"
# TERM = "xterm-256color"

[font]
size = 14.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
normal = { family = "MesloLGS Nerd Font Mono" }
bold = { family = "MesloLGS Nerd Font Mono" }
italic = { family = "MesloLGS Nerd Font Mono" }
bold_italic = { family = "MesloLGS Nerd Font Mono" }

[window]
# position = {x = 0, y = 0}
# dimensions = { columns = 107, lines = 53 }
dynamic_padding = false
startup_mode = "Windowed"
decorations = "transparent"
opacity = 0.75
padding = { x = 10, y = 25 }
dynamic_title = true
blur = true
option_as_alt = "OnlyLeft"

[selection]
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
unfocused_hollow = true
blink_interval = 600
style = { shape = "Block", blinking = "Always" }

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[general]

live_config_reload = true

[terminal]
# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Use the custom fish function 'ct <theme-title>' to change theme.
# The themes are located in the folder '~/.config/alacritty/themes/themes'.
# <theme-title> must be without the .toml file extension
# import = ["~/.config/alacritty/atm_theme.toml"]

shell.program = "/bin/zsh"
# shell.args = ["-l", "-c", "zellij attach || zellij"]
shell.args = ["-l", "-c", "zellij attach || zellij"]
